ETDA = {
    '0-day': 'Exploit',
    'ATM malware': 'Trojan-Banker',
    'Auto updater': 'Downloader',
    'Backdoor': 'Backdoor',
    'Banking trojan': 'Trojan',
    'Big Game Hunting': 'Trojan-Ransom',
    'Botnet': 'Net-Worm',
    'Credential stealer': 'Trojan-PSW',
    'DDoS': 'Trojan-DDoS',
    'Dropper': 'Trojan-Dropper',
    'Exfiltration': 'Backdoor',
    'ICS malware': 'Virus',
    'Info stealer': 'Trojan-PSW',
    'Keylogger': 'Trojan-Spy',
    'Loader': 'Trojan-Downloader',
    'Miner': 'Trojan',
    'POS malware': 'Trojan-Banker',
    'Poisoning': 'Virus',
    'Ransomware': 'Trojan-Ransom',
    'Downloader': 'Downloader',
    'Remote command': 'Backdoor',
    'Rootkit': 'Rootkit',
    'SWIFT malware': 'Trojan-Banker',
    'Wiper': 'Virus',
    'Control panel': 'HackTool',
    'Worm': 'Worm',
    'Reconnaissance': 'Monitor'
}

VT = {
    "adware": "Adware",
    "banker": "Trojan-Banker",
    "downloader": "Trojan-Downloader",
    "dropper": "Trojan-Dropper",
    "fakeav": "Trojan-FakeAV",
    "hacktool": "HackTool",
    "miner": "Trojan",
    "phishing": "Phishing",
    "pua": "RiskTool",
    "ransomware": "Trojan-Ransom",
    "spyware": "Trojan-Spy",
    "trojan": "Trojan",
    "virus": "Virus",
    "worm": "Worm"
}

TL = {
    'Spam': 1,
    'RiskTool': 1,
    'Server-Telnet': 1,
    'Server-FTP': 1,
    'Server-Proxy': 1,
    'Server-Web': 1,
    'Client-IRC': 1,
    'Client-P2P': 1,
    'Client-SMTP': 1,
    'Dialer': 1,
    'FraudTool': 1,
    'Downloader': 1,
    'Monitor': 1,
    'WebToolbar': 2,
    'NetTool': 1,
    'PSWTool': 1,
    'RemoteAdmin': 1,
    'Adware': 1,
    'Phishing': 2,
    'HackTool': 1,
    'Hoax': 2,
    'Flooder': 1,
    'IM-Flooder': 1,
    'SMS-Flooder': 1,
    'Email-Flooder': 1,
    'Spoofer': 1,
    'Constructor': 1,
    'VirTool': 2,
    'DoS': 2,
    'Trojan': 3,
    'Exploit': 3,
    'Trojan-FakeAV': 2,
    'Trojan-ArcBomb': 2,
    'Trojan-DDoS': 2,
    'Trojan-Proxy': 3,
    'Trojan-Notifier': 3,
    'Trojan-Clicker': 2,
    'Trojan-Downloader': 3,
    'Trojan-Dropper': 3,
    'Trojan-Ransom': 3,
    'Trojan-Mailfinder': 3,
    'Trojan-Spy': 3,
    'Trojan-IM': 3,
    'Trojan-SMS': 3,
    'Trojan-GameThief': 3,
    'Trojan-PSW': 3,
    'Trojan-Banker': 3,
    'Backdoor': 3,
    'Rootkit': 3,
    'Bootkit': 3,
    'Virus': 3,
    'Worm': 3,
    'IRC-Worm': 3,
    'IM-Worm': 3,
    'P2P-Worm': 3,
    'Email-Worm': 3,
    'Net-Worm': 3
}
